# Generated by Django 6.0 on 2025-12-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_freq', models.FloatField()),
                ('stop_freq', models.FloatField()),
                ('image_path', models.CharField(max_length=255)),
                ('raw_data', models.JSONField(default=list)),
            ],
        ),
    ]
